services:

  jenkins-docker:
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    ports:
      - '2376:2376'

  jenkins-blueocean:
    depends_on:
      - jenkins-docker
    image: myjenkins-blueocean:2.375.1-1    
    restart: on-failure
    ports:
      - '8081:8080'
      - '50000:50000'
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
